#!/usr/bin/env python3
"""Render the NAS-OS brand mark: web/icon.svg plus every PNG size the panel serves.

Why a renderer instead of a checked-in PNG set: the SVG and the PNGs have to agree, and
the only way to guarantee that is to generate both from ONE description of the shape.
The shape lives in LAYERS below; everything else is mechanical.

stdlib only, on purpose — this runs on the NAS itself, which has no rsvg/inkscape/PIL and
should not grow a toolchain to redraw an icon. Shapes are signed distance functions, so
antialiasing falls out of the distance (alpha = how far inside the edge the pixel centre
is) instead of needing supersampling.

Usage: python3 tools/make-icons.py [web_dir]
"""
import math, os, struct, sys, zlib

# --- the mark ---------------------------------------------------------------
# The letter N, with the diagonal carrying the colour: the stroke that crosses the box
# is the data path through it, the two uprights are the box itself. A letterform is read
# faster than any pictogram at 16 px, and it makes no claim about hardware — which is
# what the raspberry it replaced was doing wrong.
#
# Everything is drawn from LAYERS below, painted in order over the plate. Each layer is
# a colour plus a signed distance function in the 256x256 mark space, so every size is
# the same drawing rather than a resampled screenshot of a bigger one.
GROUND = "#1E2329"      # graphite plate
GLYPH  = "#EAF4F1"      # off-white uprights
LIVE   = "#6CC04A"      # the diagonal — the live/data stroke

BOX     = 256.0
PLATE_R = 56.0
STROKE  = 26.0          # every stroke of the letter, round caps
LX, RX  = 86.0, 170.0   # x of the left and right uprights
TOP, BOT = 72.0, 184.0  # y of the letter's top and bottom


def _hex(c):
    c = c.lstrip("#")
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def _sd_round_rect(x, y, rx, ry, rw, rh, r):
    """Signed distance to a rounded rectangle given by corner + size."""
    cx, cy = rx + rw / 2.0, ry + rh / 2.0
    hx, hy = rw / 2.0 - r, rh / 2.0 - r
    dx, dy = abs(x - cx) - hx, abs(y - cy) - hy
    return math.hypot(max(dx, 0.0), max(dy, 0.0)) + min(max(dx, dy), 0.0) - r


def _sd_segment(x, y, ax, ay, bx, by):
    pax, pay = x - ax, y - ay
    bax, bay = bx - ax, by - ay
    h = (pax * bax + pay * bay) / (bax * bax + bay * bay)
    h = 0.0 if h < 0.0 else (1.0 if h > 1.0 else h)
    return math.hypot(pax - bax * h, pay - bay * h)


def _sd_stroke(x, y, ax, ay, bx, by):
    return _sd_segment(x, y, ax, ay, bx, by) - STROKE / 2.0


# painted in order: the diagonal first, the uprights over it, so the joints stay clean
LAYERS = (
    (LIVE,  lambda x, y: _sd_stroke(x, y, LX, TOP, RX, BOT)),
    (GLYPH, lambda x, y: min(_sd_stroke(x, y, LX, BOT, LX, TOP),
                             _sd_stroke(x, y, RX, BOT, RX, TOP))),
)


def _cov(d, scale):
    """Distance (mark units) -> pixel coverage 0..1. `scale` = mark units per pixel."""
    a = 0.5 - d / scale
    return 0.0 if a <= 0.0 else (1.0 if a >= 1.0 else a)


def render(size):
    """RGBA bytes for one square icon."""
    ground = _hex(GROUND)
    layers = [(_hex(c), f) for c, f in LAYERS]
    scale = BOX / size                      # mark units per output pixel
    rows = []
    for py in range(size):
        y = (py + 0.5) * scale
        row = bytearray()
        for px in range(size):
            x = (px + 0.5) * scale
            a_plate = _cov(_sd_round_rect(x, y, 0.0, 0.0, BOX, BOX, PLATE_R), scale)
            if a_plate <= 0.0:
                row += b"\0\0\0\0"
                continue
            r, g, b = ground
            for col, sdf in layers:
                cov = _cov(sdf(x, y), scale)
                if cov > 0.0:
                    r = r + (col[0] - r) * cov
                    g = g + (col[1] - g) * cov
                    b = b + (col[2] - b) * cov
            row += bytes((int(r + 0.5), int(g + 0.5), int(b + 0.5),
                          int(a_plate * 255 + 0.5)))
        rows.append(bytes(row))
    return rows


def write_png(path, size):
    rows = render(size)
    raw = b"".join(b"\0" + r for r in rows)          # filter byte 0 per scanline
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c))
    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw, 9))
           + chunk(b"IEND", b""))
    with open(path, "wb") as f:
        f.write(png)
    return len(png)


SVG = '''<svg xmlns="http://www.w3.org/2000/svg" aria-label="NAS-OS" role="img" viewBox="0 0 256 256">
  <!-- NAS-OS brand mark: the letter N, its diagonal carrying the colour — the data path
       through the box, the uprights the box itself. Generated by tools/make-icons.py,
       which renders every PNG size from these same numbers; edit the shape THERE, not
       here, or the SVG and the icons drift apart. -->
  <rect width="256" height="256" rx="{plate_r:g}" fill="{ground}"/>
  <path d="M{lx:g} {top:g} L{rx:g} {bot:g}" fill="none" stroke="{live}"
        stroke-width="{sw:g}" stroke-linecap="round"/>
  <path d="M{lx:g} {bot:g} V{top:g}" fill="none" stroke="{glyph}"
        stroke-width="{sw:g}" stroke-linecap="round"/>
  <path d="M{rx:g} {bot:g} V{top:g}" fill="none" stroke="{glyph}"
        stroke-width="{sw:g}" stroke-linecap="round"/>
</svg>
'''


def main():
    web = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "web")
    with open(os.path.join(web, "icon.svg"), "w") as f:
        f.write(SVG.format(plate_r=PLATE_R, ground=GROUND, glyph=GLYPH, live=LIVE,
                           lx=LX, rx=RX, top=TOP, bot=BOT, sw=STROKE))
    print("icon.svg")
    for name, size in (("favicon-16.png", 16), ("favicon-32.png", 32),
                       ("icon-16.png", 16), ("icon-32.png", 32),
                       ("icon-180.png", 180), ("icon-192.png", 192),
                       ("icon-512.png", 512), ("apple-touch-icon.png", 180)):
        n = write_png(os.path.join(web, name), size)
        print("%-22s %4dpx  %6d B" % (name, size, n))


if __name__ == "__main__":
    main()
